### ISSUE TITLE
Git clone only works over https

### ISSUE THREAD

**Issue by krakankrakan** [stg-tud/apsa#8]
Hello,

i just wanted to mention that the command for cloning the example repo does not work:

`git clone --depth 1 git@bitbucket.org:OPAL-Project/myopalproject.git Project`

Instead, https has to be used for git. What worked for me was:

`git clone --depth 1 https://bitbucket.org/OPAL-Project/myopalproject Project`

Hope it is helpful for anyone running in the same problem.

**Comment by krakankrakan** [comment]
The "not working" command is listed in the first task and the OPAL basics pdf.

**Comment by Delors** [comment]
Thanks for pointing this out - the shown command only works if you are "logged in". But this doesn't make sense in general. 

I updated the ".md" files and I will recreate the ".pdf"s in due time.
